// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6wf76Scll4EbgoqKE8Dz6Qi7k_uFnsnU',
    appId: '1:658427068993:web:cfc2320740f3548e213cc0',
    messagingSenderId: '658427068993',
    projectId: 'flutterfire-notes-app',
    authDomain: 'flutterfire-notes-app.firebaseapp.com',
    storageBucket: 'flutterfire-notes-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEfzbQR7JnVGdTajiTkdG2kO0KzWSt-wk',
    appId: '1:658427068993:android:e7c02796467a4bf2213cc0',
    messagingSenderId: '658427068993',
    projectId: 'flutterfire-notes-app',
    storageBucket: 'flutterfire-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCASsbwRAw01yW2a_IraC7yFfgHySYRCwk',
    appId: '1:658427068993:ios:bf6f961325d0baa1213cc0',
    messagingSenderId: '658427068993',
    projectId: 'flutterfire-notes-app',
    storageBucket: 'flutterfire-notes-app.appspot.com',
    iosClientId: '658427068993-8cd7ts7aofkl72lrbo03cuvnr9p3o63f.apps.googleusercontent.com',
    iosBundleId: 'com.topdev',
  );
}
